{{- if not .Values.ignoreHelmHooks }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: config-pipelines
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccount: default
      serviceAccountName: default
      containers:
      - name: job
        image: "quay.io/openshift/origin-cli:latest"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            echo "Waiting for CRD 'tektonconfigs.operator.tekton.dev' to be available..."
            until oc get crd tektonconfigs.operator.tekton.dev &> /dev/null; do
              echo "CRD 'tektonconfigs.operator.tekton.dev' not found. Retrying in 10 seconds..."
              sleep 10
            done
            echo "CRD 'tektonconfigs.operator.tekton.dev' is now available."

            echo "Waiting for TektonConfig 'config' to be created..."

            # Loop to check for the resource's existence
            until oc get tektonconfig config &> /dev/null; do
              echo "TektonConfig 'config' not yet created. Retrying in 10 seconds..."
              sleep 10
            done
            echo "TektonConfig 'config' has been created. Proceeding with patch."
            
            # Apply the patch once the resource is confirmed to exist
            oc patch tektonconfig config --type=merge -p '{"spec":{"pipeline":{"coschedule":"disabled"}}}'
            echo "Successfully patched TektonConfig 'config'."
{{- end }}