{{- if not .Values.ignoreHelmHooks }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: config-pipelines
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccount: default
      serviceAccountName: default
      containers:
      - name: job
        image: "quay.io/openshift/origin-cli:latest"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - | # Disable affinity assitant: https://access.redhat.com/solutions/7128120
            oc patch tektonconfig.operator.tekton.dev/config --patch '{"spec":{"pipeline":{"coschedule":"disabled"}}}' --type=merge
{{- end }}